import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import LoginBtn from '../clientComponents/LoginBtn'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { getServerSession } from 'next-auth'
import LogOutBtn from '../clientComponents/LogOutBtn'
import { SocketProvider } from '@/clientComponents/socket-provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  
  console.log('session :', session);

  return ( 
    <html>
      <body>
        <div className="navBar">
          <Link href="/">Home</Link>
          <Link href="/register">소환사 등록</Link>
          {
            session ? <span>
              <span className='user-email'>{session.user.email}님 환영합니다</span>
               <LogOutBtn/>
              </span> : <LoginBtn/> 
          }
        </div>
        {children}
      </body>
    </html>
  )
}
